version: '3.8'

services:
  task-board-pg:
    image: postgres:17-alpine
    container_name: tasks-board-pg
    environment:
      POSTGRES_USER: patryk
      POSTGRES_PASSWORD: patryk123
      POSTGRES_DB: task_board
    ports:
      - "5432:5432"
    volumes:
      - task-board-pg-data:/var/lib/postgresql/data
    networks:
      - task-board-network

  task-board-backend:
    build:
      context: task-board-backend
      dockerfile: Dockerfile
    image: task-board-backend
    container_name: tasks-board-backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_TASK_BOARD_HOST=task-board-pg
      - POSTGRES_TASK_BOARD_PORT=5432
      - POSTGRES_TASK_BOARD_DATABASE=task_board
      - POSTGRES_TASK_BOARD_USERNAME=patryk
      - POSTGRES_TASK_BOARD_PASSWORD=patryk123
    networks:
      - task-board-network
    depends_on:
      - task-board-pg

#  task-board-frontend:
#    build:
#      context: task-board-frontend
#      dockerfile: Dockerfile
#    container_name: task-board-frontend
#    ports:
#      - "80:80"
#    networks:
#      - task-board-network
#    depends_on:
#      - task-board-backend

volumes:
  task-board-pg-data:

networks:
  task-board-network: