version: '3.8'

services:

  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - task-board-auth
      - task-board-backend
      - task-board-frontend
    networks:
      - task-board-network

  task-board-auth-pg:
    image: postgres:17-alpine
    container_name: task-board-auth-pg
    environment:
      POSTGRES_USER: ${POSTGRES_TASK_BOARD_AUTH_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_TASK_BOARD_AUTH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TASK_BOARD_AUTH_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - task-board-auth-pg-data:/var/lib/postgresql/data
    networks:
      - task-board-network

  task-board-auth:
    build:
      context: task-board-auth
      dockerfile: Dockerfile
    image: task-board-auth
    container_name: task-board-auth
    environment:
      - POSTGRES_TASK_BOARD_AUTH_HOST=task-board-auth-pg
      - POSTGRES_TASK_BOARD_AUTH_PORT=5432
      - POSTGRES_TASK_BOARD_AUTH_DATABASE=${POSTGRES_TASK_BOARD_AUTH_DATABASE}
      - POSTGRES_TASK_BOARD_AUTH_USERNAME=${POSTGRES_TASK_BOARD_AUTH_USERNAME}
      - POSTGRES_TASK_BOARD_AUTH_PASSWORD=${POSTGRES_TASK_BOARD_AUTH_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - OAUTH2_GITHUB_CLIENT_ID=${OAUTH2_GITHUB_CLIENT_ID}
      - OAUTH2_GITHUB_CLIENT_SECRET=${OAUTH2_GITHUB_CLIENT_SECRET}
      - OAUTH2_GOOGLE_CLIENT_ID=${OAUTH2_GOOGLE_CLIENT_ID}
      - OAUTH2_GOOGLE_CLIENT_SECRET=${OAUTH2_GOOGLE_CLIENT_SECRET}
    networks:
      - task-board-network
    depends_on:
      - task-board-auth-pg

  task-board-backend-pg:
    image: postgres:17-alpine
    container_name: task-board-backend-pg
    environment:
      POSTGRES_USER: ${POSTGRES_TASK_BOARD_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_TASK_BOARD_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TASK_BOARD_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - task-board-backend-pg-data:/var/lib/postgresql/data
    networks:
      - task-board-network

  task-board-backend:
    build:
      context: task-board-backend
      dockerfile: Dockerfile
    image: task-board-backend
    container_name: task-board-backend
    environment:
      - POSTGRES_TASK_BOARD_HOST=task-board-backend-pg
      - POSTGRES_TASK_BOARD_PORT=5432
      - POSTGRES_TASK_BOARD_DATABASE=${POSTGRES_TASK_BOARD_DATABASE}
      - POSTGRES_TASK_BOARD_USERNAME=${POSTGRES_TASK_BOARD_USERNAME}
      - POSTGRES_TASK_BOARD_PASSWORD=${POSTGRES_TASK_BOARD_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - task-board-network
    depends_on:
      - task-board-backend-pg

  task-board-frontend:
    build:
      context: task-board-frontend
      dockerfile: Dockerfile
      args:
        - OAUTH2_GOOGLE_CLIENT_ID=${OAUTH2_GOOGLE_CLIENT_ID}
        - OAUTH2_GITHUB_CLIENT_ID=${OAUTH2_GITHUB_CLIENT_ID}
    image: task-board-frontend
    container_name: task-board-frontend
    networks:
      - task-board-network
    depends_on:
      - task-board-backend

volumes:
  task-board-backend-pg-data:
  task-board-auth-pg-data:

networks:
  task-board-network: