spring:
  application:
    name: task-board-auth
  datasource:
    url: jdbc:postgresql://${POSTGRES_TASK_BOARD_AUTH_HOST:localhost}:${POSTGRES_TASK_BOARD_AUTH_PORT:5432}/${POSTGRES_TASK_BOARD_AUTH_DATABASE:task_board_auth}
    username: ${POSTGRES_TASK_BOARD_AUTH_USERNAME:auth}
    password: ${POSTGRES_TASK_BOARD_AUTH_PASSWORD:auth123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: public

jwt:
  secret: "ToJestMojBardzoSuperTajnyKluczKtoregoNiktNieZgadnie12345!@#$%"
  expiration-ms: 900000